defaults:
  -
    scope:
      path: ""
    values:
      layout: "basic"
      section: "hibi"
      icon: "/assets/art/kbwrior.png"
  -
    scope:
      path: "mods"
    values:
      layout: "mod"
      section: "hibi's mods"
  -
    scope:
      path: "mods/doc"
    values:
      layout: "basic"
      description: "User's Manual and Technical Reference"
      section: "hibi's mods"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      section: "hibi's blog"
collections:
  posts:
    relative_directory: "blog/"
    permalink: "blog/post/:title"
kramdown:
  parse_block_html: true
  header_offset: 1
  syntax_highlighter_opts:
    disable: true
